AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Second Watch Network API - FastAPI on Lambda with WebSocket - Updated 2025-12-23

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.12
    Environment:
      Variables:
        APP_ENV: production
        DEBUG: "False"

Parameters:
  DatabaseUrl:
    Type: String
    Description: PostgreSQL connection string
    NoEcho: true
  CognitoUserPoolId:
    Type: String
    Description: AWS Cognito User Pool ID
  CognitoClientId:
    Type: String
    Description: AWS Cognito Client ID
  CognitoRegion:
    Type: String
    Default: us-east-1
  S3AvatarsBucket:
    Type: String
    Description: S3 bucket for avatar uploads
  S3BacklotBucket:
    Type: String
    Description: S3 bucket for backlot files
  S3BacklotFilesBucket:
    Type: String
    Description: S3 bucket for backlot PDF files
  FrontendUrl:
    Type: String
    Default: https://www.secondwatchnetwork.com
  StripeSecretKey:
    Type: String
    NoEcho: true
    Default: ""
  StripeWebhookSecret:
    Type: String
    NoEcho: true
    Default: ""
  AnthropicApiKey:
    Type: String
    NoEcho: true
    Default: ""
  ResendApiKey:
    Type: String
    NoEcho: true
    Default: ""
  WebSocketConnectionsTableName:
    Type: String
    Default: second-watch-websocket-connections
    Description: DynamoDB table for WebSocket connections

Resources:
  # ============================================================================
  # Main API Lambda
  # ============================================================================
  SecondWatchApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handler.handler
      Description: Second Watch Network FastAPI Backend
      Architectures:
        - x86_64
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          COGNITO_CLIENT_ID: !Ref CognitoClientId
          COGNITO_REGION: !Ref CognitoRegion
          AWS_S3_AVATARS_BUCKET: !Ref S3AvatarsBucket
          AWS_S3_BACKLOT_BUCKET: !Ref S3BacklotBucket
          AWS_S3_BACKLOT_FILES_BUCKET: !Ref S3BacklotFilesBucket
          FRONTEND_URL: !Ref FrontendUrl
          STRIPE_SECRET_KEY: !Ref StripeSecretKey
          STRIPE_WEBHOOK_SECRET: !Ref StripeWebhookSecret
          ANTHROPIC_API_KEY: !Ref AnthropicApiKey
          RESEND_API_KEY: !Ref ResendApiKey
      Events:
        ApiRoot:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
        ApiProxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        # Keep-warm: EventBridge pings /health every 5 minutes
        KeepWarm:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Description: Keep Lambda warm to reduce cold start latency
            Input: '{"httpMethod": "GET", "path": "/health", "requestContext": {"http": {"method": "GET", "path": "/health"}}, "headers": {"X-Warmup-Ping": "true"}, "isBase64Encoded": false}'
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3AvatarsBucket
        - S3CrudPolicy:
            BucketName: !Ref S3BacklotBucket
        - S3CrudPolicy:
            BucketName: !Ref S3BacklotFilesBucket
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:*
              Resource: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPoolId}"

  # ============================================================================
  # WebSocket API for Real-Time Communications
  # ============================================================================

  # DynamoDB Table for Connection Management
  WebSocketConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref WebSocketConnectionsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # WebSocket API
  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: SecondWatchWebSocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
      Description: Second Watch Network WebSocket API for real-time communications

  # WebSocket Lambda Function
  WebSocketFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: websocket/
      Handler: handler.handler
      Runtime: python3.12
      Timeout: 29
      MemorySize: 256
      Description: WebSocket handler for real-time communications
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref WebSocketConnectionsTableName
          DATABASE_URL: !Ref DatabaseUrl
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          COGNITO_CLIENT_ID: !Ref CognitoClientId
          COGNITO_REGION: !Ref CognitoRegion
          LOG_LEVEL: INFO
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref WebSocketConnectionsTableName
        - Statement:
            - Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource:
                - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*"

  # Lambda Permission for WebSocket API
  WebSocketFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebSocketFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*"

  # WebSocket Routes and Integrations
  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketFunction.Arn}/invocations"

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Sub "integrations/${ConnectIntegration}"

  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketFunction.Arn}/invocations"

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      Target: !Sub "integrations/${DisconnectIntegration}"

  DefaultIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketFunction.Arn}/invocations"

  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $default
      AuthorizationType: NONE
      Target: !Sub "integrations/${DefaultIntegration}"

  # WebSocket Deployment and Stage
  WebSocketDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
      - DefaultRoute
    Properties:
      ApiId: !Ref WebSocketApi

  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WebSocketApi
      StageName: prod
      DeploymentId: !Ref WebSocketDeployment
      DefaultRouteSettings:
        ThrottlingBurstLimit: 500
        ThrottlingRateLimit: 1000

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
  WebSocketApiUrl:
    Description: "WebSocket API URL"
    Value: !Sub "wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  WebSocketConnectionsTableName:
    Description: "DynamoDB table for WebSocket connections"
    Value: !Ref WebSocketConnectionsTable
