AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Second Watch Network API - FastAPI on Lambda with WebSocket - Updated 2026-02-14b

Globals:
  Function:
    Timeout: 30
    MemorySize: 2048
    Runtime: python3.12
    Environment:
      Variables:
        APP_ENV: production
        DEBUG: "False"

Parameters:
  DatabaseUrl:
    Type: String
    Description: PostgreSQL connection string
    NoEcho: true
  CognitoUserPoolId:
    Type: String
    Description: AWS Cognito User Pool ID
  CognitoClientId:
    Type: String
    Description: AWS Cognito Client ID
  CognitoRegion:
    Type: String
    Default: us-east-1
  CognitoClientSecret:
    Type: String
    Description: AWS Cognito Client Secret (optional for public clients)
    NoEcho: true
    Default: ""
  S3AvatarsBucket:
    Type: String
    Description: S3 bucket for avatar uploads
  S3BacklotBucket:
    Type: String
    Description: S3 bucket for backlot files
  S3BacklotFilesBucket:
    Type: String
    Description: S3 bucket for backlot PDF files
  S3VideoMastersBucket:
    Type: String
    Description: S3 bucket for video master files
    Default: swn-video-masters-517220555400
  S3VideoPublishBucket:
    Type: String
    Description: S3 bucket for published video files
    Default: swn-video-publish-517220555400
  S3DownloadsBucket:
    Type: String
    Description: S3 bucket for downloadable files
    Default: swn-downloads-517220555400
  FrontendUrl:
    Type: String
    Default: https://www.secondwatchnetwork.com
  StripeSecretKey:
    Type: String
    NoEcho: true
    Default: ""
  StripePublishableKey:
    Type: String
    Default: ""
  StripeWebhookSecret:
    Type: String
    NoEcho: true
    Default: ""
  StripePremiumPriceId:
    Type: String
    Description: Stripe price ID for premium monthly subscription
    Default: ""
  StripePremiumYearlyPriceId:
    Type: String
    Description: Stripe price ID for premium yearly subscription
    Default: ""
  StripeBacklotMonthlyPriceId:
    Type: String
    Description: Stripe price ID for Backlot monthly subscription
    Default: ""
  StripeBacklotYearlyPriceId:
    Type: String
    Description: Stripe price ID for Backlot yearly subscription
    Default: ""
  StripeOrderBasePriceId:
    Type: String
    Description: Stripe price ID for Order BASE tier ($50/mo)
    Default: ""
  StripeOrderStewardPriceId:
    Type: String
    Description: Stripe price ID for Order STEWARD tier ($100/mo)
    Default: ""
  StripeOrderPatronPriceId:
    Type: String
    Description: Stripe price ID for Order PATRON tier ($250/mo)
    Default: ""
  AnthropicApiKey:
    Type: String
    NoEcho: true
    Default: ""
  OpenAiApiKey:
    Type: String
    Description: OpenAI API key for AI features
    NoEcho: true
    Default: ""
  ResendApiKey:
    Type: String
    NoEcho: true
    Default: ""
  ResendWebhookSigningSecret:
    Type: String
    NoEcho: true
    Default: ""
    Description: Resend webhook signing secret for verifying inbound email webhooks
  EmailFromAddress:
    Type: String
    Description: Email sender address
    Default: noreply@theswn.com
  EmailFromName:
    Type: String
    Description: Email sender display name
    Default: Second Watch Network
  SuperadminEmail:
    Type: String
    Description: Email address for auto-granted superadmin
    Default: ""
  WebSocketConnectionsTableName:
    Type: String
    Default: second-watch-websocket-connections
    Description: DynamoDB table for WebSocket connections
  CloudFrontVideoDomain:
    Type: String
    Description: CloudFront distribution domain for video CDN
    Default: d1u4sv04wott56.cloudfront.net
  CloudFrontVideoDistributionId:
    Type: String
    Description: CloudFront distribution ID for video CDN
    Default: E17MNILTBIP3I2
  CloudFrontKeyPairId:
    Type: String
    Description: CloudFront key pair ID for signed URLs
    Default: ""
  CloudFrontPrivateKey:
    Type: String
    Description: CloudFront private key PEM for signed URLs
    NoEcho: true
    Default: ""

Resources:
  # ============================================================================
  # Cognito Custom Email Sender (KMS Key + Lambda)
  # ============================================================================
  CognitoEmailSenderKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS key for Cognito Custom Email Sender code encryption
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowRootAccount
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Sid: AllowCognitoEncrypt
            Effect: Allow
            Principal:
              Service: cognito-idp.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:ReEncrypt*
              - kms:DescribeKey
            Resource: "*"
            Condition:
              StringEquals:
                "aws:SourceAccount": !Ref "AWS::AccountId"

  CognitoEmailSenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cognito_email_sender/
      Handler: handler.handler
      Runtime: python3.12
      Timeout: 30
      MemorySize: 256
      Description: Cognito custom email sender — branded emails via Resend
      Environment:
        Variables:
          RESEND_API_KEY: !Ref ResendApiKey
          KMS_KEY_ARN: !GetAtt CognitoEmailSenderKmsKey.Arn
          EMAIL_FROM_ADDRESS: !Ref EmailFromAddress
          EMAIL_FROM_NAME: !Ref EmailFromName
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
              Resource: !GetAtt CognitoEmailSenderKmsKey.Arn

  CognitoEmailSenderPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CognitoEmailSenderFunction
      Action: lambda:InvokeFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPoolId}"

  # ============================================================================
  # HTTP API with CORS (ensures CORS headers on gateway-level errors like 502/503)
  # ============================================================================
  ServerlessHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - OPTIONS
        AllowHeaders:
          - Authorization
          - Content-Type
          - Accept
          - Origin
          - X-Requested-With
          - X-Request-ID
        ExposeHeaders:
          - X-Request-ID
        MaxAge: 600

  # ============================================================================
  # Main API Lambda
  # ============================================================================
  SecondWatchApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handler.handler
      Description: Second Watch Network FastAPI Backend
      Timeout: 60
      MemorySize: 4096
      AutoPublishAlias: live
      Architectures:
        - arm64
      Layers:
        - arn:aws:lambda:us-east-1:517220555400:layer:weasyprint-deps-arm64:3
      Environment:
        Variables:
          # System libraries (WeasyPrint layer)
          LD_LIBRARY_PATH: /opt/lib
          # Deploy marker (change to force env var refresh)
          DEPLOY_VERSION: "2026-02-14-01"
          # Database
          DATABASE_URL: !Ref DatabaseUrl
          # Auth
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          COGNITO_CLIENT_ID: !Ref CognitoClientId
          COGNITO_REGION: !Ref CognitoRegion
          COGNITO_CLIENT_SECRET: !Ref CognitoClientSecret
          SUPERADMIN_EMAIL: !Ref SuperadminEmail
          # S3 Buckets
          AWS_S3_AVATARS_BUCKET: !Ref S3AvatarsBucket
          AWS_S3_BACKLOT_BUCKET: !Ref S3BacklotBucket
          AWS_S3_BACKLOT_FILES_BUCKET: !Ref S3BacklotFilesBucket
          AWS_S3_VIDEO_MASTERS_BUCKET: !Ref S3VideoMastersBucket
          AWS_S3_VIDEO_PUBLISH_BUCKET: !Ref S3VideoPublishBucket
          S3_DOWNLOADS_BUCKET: !Ref S3DownloadsBucket
          # Frontend
          FRONTEND_URL: !Ref FrontendUrl
          # Stripe
          STRIPE_SECRET_KEY: !Ref StripeSecretKey
          STRIPE_PUBLISHABLE_KEY: !Ref StripePublishableKey
          STRIPE_WEBHOOK_SECRET: !Ref StripeWebhookSecret
          STRIPE_PREMIUM_PRICE_ID: !Ref StripePremiumPriceId
          STRIPE_PREMIUM_YEARLY_PRICE_ID: !Ref StripePremiumYearlyPriceId
          STRIPE_BACKLOT_MONTHLY_PRICE_ID: !Ref StripeBacklotMonthlyPriceId
          STRIPE_BACKLOT_YEARLY_PRICE_ID: !Ref StripeBacklotYearlyPriceId
          STRIPE_ORDER_BASE_PRICE_ID: !Ref StripeOrderBasePriceId
          STRIPE_ORDER_STEWARD_PRICE_ID: !Ref StripeOrderStewardPriceId
          STRIPE_ORDER_PATRON_PRICE_ID: !Ref StripeOrderPatronPriceId
          # AI
          ANTHROPIC_API_KEY: !Ref AnthropicApiKey
          OPENAI_API_KEY: !Ref OpenAiApiKey
          # Email
          EMAIL_PROVIDER: resend
          RESEND_API_KEY: !Ref ResendApiKey
          RESEND_WEBHOOK_SIGNING_SECRET: !Ref ResendWebhookSigningSecret
          EMAIL_FROM_ADDRESS: !Ref EmailFromAddress
          EMAIL_FROM_NAME: !Ref EmailFromName
          # CloudFront / Video CDN
          CLOUDFRONT_VIDEO_DOMAIN: !Ref CloudFrontVideoDomain
          CLOUDFRONT_VIDEO_DISTRIBUTION_ID: !Ref CloudFrontVideoDistributionId
          CLOUDFRONT_KEY_PAIR_ID: !Ref CloudFrontKeyPairId
          CLOUDFRONT_PRIVATE_KEY: !Ref CloudFrontPrivateKey
          # WebSocket
          WEBSOCKET_API_ENDPOINT: !Sub "https://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
          WEBSOCKET_CONNECTIONS_TABLE: !Ref WebSocketConnectionsTableName
      Events:
        ApiRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref ServerlessHttpApi
            Path: /
            Method: ANY
        ApiProxy:
          Type: HttpApi
          Properties:
            ApiId: !Ref ServerlessHttpApi
            Path: /{proxy+}
            Method: ANY
        # Keep-warm: EventBridge pings every 1 minute to prevent cold starts
        KeepWarm:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Description: Keep Lambda warm to reduce cold start latency
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3AvatarsBucket
        - S3CrudPolicy:
            BucketName: !Ref S3BacklotBucket
        - S3CrudPolicy:
            BucketName: !Ref S3BacklotFilesBucket
        - S3CrudPolicy:
            BucketName: !Ref S3VideoMastersBucket
        - S3CrudPolicy:
            BucketName: !Ref S3VideoPublishBucket
        - S3CrudPolicy:
            BucketName: !Ref S3DownloadsBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref WebSocketConnectionsTableName
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:*
              Resource: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPoolId}"
            - Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource:
                - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*"
            - Effect: Allow
              Action:
                - geo:SearchPlaceIndexForText
                - geo:SearchPlaceIndexForPosition
                - geo:CalculateRoute
              Resource: "*"
            - Effect: Allow
              Action:
                - ecs:RunTask
                - ecs:DescribeTasks
                - ecs:StopTask
              Resource: "*"
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource: "*"
              Condition:
                StringLike:
                  iam:PassedToService: ecs-tasks.amazonaws.com

  # ============================================================================
  # WebSocket API for Real-Time Communications
  # ============================================================================

  # DynamoDB Table for Connection Management
  WebSocketConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref WebSocketConnectionsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # WebSocket API
  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: SecondWatchWebSocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
      Description: Second Watch Network WebSocket API for real-time communications

  # WebSocket Lambda Function
  WebSocketFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: websocket/
      Handler: handler.handler
      Runtime: python3.12
      Timeout: 29
      MemorySize: 256
      Description: WebSocket handler for real-time communications
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref WebSocketConnectionsTableName
          DATABASE_URL: !Ref DatabaseUrl
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          COGNITO_CLIENT_ID: !Ref CognitoClientId
          COGNITO_REGION: !Ref CognitoRegion
          LOG_LEVEL: INFO
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref WebSocketConnectionsTableName
        - Statement:
            - Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource:
                - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*"

  # Lambda Permission for WebSocket API
  WebSocketFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebSocketFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*"

  # WebSocket Routes and Integrations
  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketFunction.Arn}/invocations"

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Sub "integrations/${ConnectIntegration}"

  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketFunction.Arn}/invocations"

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      Target: !Sub "integrations/${DisconnectIntegration}"

  DefaultIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketFunction.Arn}/invocations"

  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $default
      AuthorizationType: NONE
      Target: !Sub "integrations/${DefaultIntegration}"

  # WebSocket Deployment and Stage
  WebSocketDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
      - DefaultRoute
    Properties:
      ApiId: !Ref WebSocketApi

  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WebSocketApi
      StageName: prod
      DeploymentId: !Ref WebSocketDeployment
      DefaultRouteSettings:
        ThrottlingBurstLimit: 500
        ThrottlingRateLimit: 1000

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
  WebSocketApiUrl:
    Description: "WebSocket API URL"
    Value: !Sub "wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  WebSocketConnectionsTableName:
    Description: "DynamoDB table for WebSocket connections"
    Value: !Ref WebSocketConnectionsTable
  CognitoEmailSenderFunctionArn:
    Description: "Cognito Custom Email Sender Lambda ARN"
    Value: !GetAtt CognitoEmailSenderFunction.Arn
  CognitoEmailSenderKmsKeyArn:
    Description: "KMS Key ARN for Cognito email code encryption"
    Value: !GetAtt CognitoEmailSenderKmsKey.Arn
