#!/bin/bash

# Manual Budget Actuals Testing Script
# This script helps guide manual testing of the budget actuals system

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║     Budget Actuals System - Manual Testing Guide             ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "This script will help you test the budget actuals system."
echo ""
echo "Prerequisites:"
echo "  ✓ Backend running on localhost:8000"
echo "  ✓ Frontend running on localhost:8080"
echo "  ✓ User account with approval permissions"
echo "  ✓ Backlot project with pending expenses"
echo ""

# Check if services are running
echo "Checking if services are running..."
echo ""

if curl -s http://localhost:8000/health > /dev/null; then
    echo "✓ Backend (localhost:8000) - RUNNING"
else
    echo "✗ Backend (localhost:8000) - NOT RUNNING"
    echo "  Start with: cd backend && source venv/bin/activate && uvicorn app.main:app --reload"
fi

if curl -s http://localhost:8080 > /dev/null; then
    echo "✓ Frontend (localhost:8080) - RUNNING"
else
    echo "✗ Frontend (localhost:8080) - NOT RUNNING"
    echo "  Start with: cd frontend && npm run dev"
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""

read -p "Press ENTER to continue with testing instructions..."

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  STEP 1: Navigate to Budget Tab (Initial State)              ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "1. Open http://localhost:8080 in your browser"
echo "2. Log in with your credentials"
echo "3. Navigate to Backlot"
echo "4. Click on a project"
echo "5. Click on 'Budget' tab"
echo "6. Click the 'Actual' toggle button"
echo ""
echo "What to check:"
echo "  - Is there an 'Actual' toggle button?"
echo "  - Does clicking it change the view?"
echo "  - What content is shown? (empty state or actual items)"
echo ""

read -p "Press ENTER when ready for next step..."

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  STEP 2: Monitor Network Requests                            ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "1. Open browser DevTools (F12)"
echo "2. Go to Network tab"
echo "3. Filter for 'budget-actuals'"
echo "4. Click 'Actual' toggle again"
echo ""
echo "Expected API call:"
echo "  GET /api/v1/backlot/projects/{id}/budget-actuals?include_source_details=true"
echo ""
echo "Check the response:"
echo "  - Status code 200?"
echo "  - Response body contains 'actuals' array?"
echo "  - Total amount calculated?"
echo ""

read -p "Press ENTER when ready for next step..."

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  STEP 3: Approve an Expense                                  ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "1. Go to 'Approvals' tab"
echo "2. Find a pending expense (receipt, mileage, kit rental, or per diem)"
echo "3. Click on the expense to open detail dialog"
echo "4. Keep DevTools Network tab open"
echo "5. Click 'Approve' button"
echo ""
echo "Expected Network Requests:"
echo "  - PUT/POST to approve the expense (status 200)"
echo "  - Dialog should close"
echo "  - Success message should appear"
echo ""
echo "Note: Budget actuals are created server-side,"
echo "so you won't see a budget-actuals API call here."
echo ""

read -p "Press ENTER when expense is approved..."

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  STEP 4: Verify Budget Actuals Updated                       ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "1. Go back to 'Budget' tab"
echo "2. Click 'Actual' toggle"
echo "3. Watch Network tab for:"
echo "   GET /api/v1/backlot/projects/{id}/budget-actuals"
echo ""
echo "Expected in UI:"
echo "  ✓ New line item for the approved expense"
echo "  ✓ Correct amount displayed"
echo "  ✓ Correct source type icon (receipt/mileage/kit/per diem)"
echo "  ✓ Vendor or description shown"
echo "  ✓ Category assigned correctly"
echo ""
echo "Things to verify:"
echo "  - Does the item appear?"
echo "  - Is the amount correct?"
echo "  - Is the icon/type correct?"
echo "  - Does it match the approved expense?"
echo ""

read -p "Press ENTER when ready for next step..."

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  STEP 5: Verify Estimated Budget Unchanged                   ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "1. Click 'Estimated' toggle"
echo "2. Verify the approved expense does NOT appear here"
echo "3. Estimated budget should only show manually created line items"
echo ""
echo "Expected behavior:"
echo "  - Estimated view = manual budget planning"
echo "  - Actual view = approved expenses only"
echo "  - They are separate and independent"
echo ""

read -p "Press ENTER when ready for next step..."

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  STEP 6: Test Multiple Expense Types                         ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "Repeat the approval process for each expense type:"
echo ""
echo "  [ ] Receipt - Should show receipt icon"
echo "  [ ] Mileage - Should show car icon"
echo "  [ ] Kit Rental - Should show briefcase icon"
echo "  [ ] Per Diem - Should show utensils icon"
echo ""
echo "For each type, verify:"
echo "  - Correct icon displays"
echo "  - Correct category (Travel, Equipment, Per Diem, etc.)"
echo "  - Correct line item name format"
echo "  - Amount matches approved expense"
echo ""

read -p "Press ENTER when all types tested..."

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  STEP 7: Test Duplicate Prevention                           ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "1. Find an already-approved expense"
echo "2. Try to approve it again (if UI allows)"
echo ""
echo "Expected behavior:"
echo "  - UI should prevent re-approving (button disabled/hidden)"
echo "  - OR if attempted, should show error"
echo "  - Backend logs should show: 'Source already recorded, skipping'"
echo "  - No duplicate entry in actual budget"
echo ""

read -p "Press ENTER for test summary..."

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  Test Complete - Summary Checklist                           ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "Please confirm the following:"
echo ""
echo "UI Functionality:"
echo "  [ ] Actual toggle button is visible"
echo "  [ ] Clicking toggle changes view"
echo "  [ ] Description changes ('Estimated' vs 'Actual expenses')"
echo ""
echo "Approval Flow:"
echo "  [ ] Approve button works in Approvals tab"
echo "  [ ] Success message appears"
echo "  [ ] Dialog closes after approval"
echo ""
echo "Budget Actuals:"
echo "  [ ] Approved expense appears in Actual view"
echo "  [ ] Amount is correct"
echo "  [ ] Source type icon is correct"
echo "  [ ] Vendor/description displays"
echo "  [ ] Category assignment is correct"
echo ""
echo "Data Integrity:"
echo "  [ ] No duplicates created"
echo "  [ ] Estimated budget unchanged"
echo "  [ ] Totals calculate correctly"
echo ""
echo "Network Requests:"
echo "  [ ] budget-actuals API calls successful (200 status)"
echo "  [ ] No console errors"
echo "  [ ] No failed network requests"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Testing complete!"
echo ""
echo "If you found any issues, please document:"
echo "  1. Steps to reproduce"
echo "  2. Expected vs actual behavior"
echo "  3. Screenshots"
echo "  4. Browser console errors"
echo "  5. Network request/response details"
echo ""
echo "For detailed investigation report, see:"
echo "  tests/e2e/BUDGET_ACTUALS_INVESTIGATION_REPORT.md"
echo ""
echo "═══════════════════════════════════════════════════════════════"
