// US States list for dropdown
export const US_STATES = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
  { value: 'DC', label: 'District of Columbia' },
  { value: 'PR', label: 'Puerto Rico' },
  { value: 'VI', label: 'U.S. Virgin Islands' },
  { value: 'GU', label: 'Guam' },
  { value: 'AS', label: 'American Samoa' },
  { value: 'MP', label: 'Northern Mariana Islands' },
] as const;

// Film production regions/hubs for dropdown
export const PRODUCTION_REGIONS = [
  { value: 'los-angeles', label: 'Los Angeles' },
  { value: 'new-york', label: 'New York' },
  { value: 'atlanta', label: 'Atlanta' },
  { value: 'chicago', label: 'Chicago' },
  { value: 'austin', label: 'Austin' },
  { value: 'new-orleans', label: 'New Orleans' },
  { value: 'miami', label: 'Miami' },
  { value: 'san-francisco', label: 'San Francisco' },
  { value: 'portland', label: 'Portland' },
  { value: 'seattle', label: 'Seattle' },
  { value: 'denver', label: 'Denver' },
  { value: 'nashville', label: 'Nashville' },
  { value: 'detroit', label: 'Detroit' },
  { value: 'phoenix', label: 'Phoenix' },
  { value: 'boston', label: 'Boston' },
  { value: 'philadelphia', label: 'Philadelphia' },
  { value: 'las-vegas', label: 'Las Vegas' },
  { value: 'san-diego', label: 'San Diego' },
  { value: 'albuquerque', label: 'Albuquerque' },
  { value: 'pittsburgh', label: 'Pittsburgh' },
  { value: 'dallas', label: 'Dallas' },
  { value: 'houston', label: 'Houston' },
  { value: 'minneapolis', label: 'Minneapolis' },
  { value: 'salt-lake-city', label: 'Salt Lake City' },
  { value: 'hawaii', label: 'Hawaii' },
  { value: 'other', label: 'Other' },
] as const;

export type USState = typeof US_STATES[number];
export type ProductionRegion = typeof PRODUCTION_REGIONS[number];
